// AUTO-GENERATED by GenerateEmbeddedConfig.ps1 on 2026-03-22 14:18:01
// DO NOT EDIT — overwritten on every build from .env
namespace LustsDepotDownloaderPro.Utils;
public static partial class EmbeddedConfig
{
    static EmbeddedConfig()
    {
        _GitHubApiKeyPat     = "";
        _GitHubApiKeyClassic = "";
        _SteamWebApiKey      = "";
        _SteamCdnToken       = "";
        _SteamSharedSecret   = "";
        _SteamIdentitySecret = "";
        _SteamRefreshToken   = "";
        _ManifestHubApiKey   = "";
        _DepotBoxApiKey      = "";
        _DefaultCdnRegion    = null;
        _DefaultWorkers      = 32;
        _AppVersion          = "1.5.0";
    }
}
